language: python
python:
- '2.7'

addons:
  postgresql: "9.3"

install:
  - pip install -r requirements.txt

script:
  - py.test

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
