# see: https://github.com/tomchristie/mkdocs/blob/master/mkdocs.yml
site_name: {{ cookiecutter.site_name }}
site_description: {{ cookiecutter.site_description }}

pages:
- ['index.md', 'Home']
- ['deploy.md', 'Deploy']

theme: 'mkdocs'
theme_center_lead: true

# directory to output HTML build
site_dir: _docs_html
